Repository depromeet/WalWal-server, pull requests merged in 2024-10, with the labels that each got.

#285 피드 신고 기능 구현
  src/main/java/com/depromeet/stonebed/domain/report/api/ReportController.java
  src/main/java/com/depromeet/stonebed/domain/report/application/ReportService.java
  src/main/java/com/depromeet/stonebed/domain/report/dao/ReportRepository.java
  src/main/java/com/depromeet/stonebed/domain/report/domain/Report.java
  src/main/java/com/depromeet/stonebed/domain/report/dto/request/ReportRequest.java
  src/main/java/com/depromeet/stonebed/domain/report/dto/response/ReportReasonResponse.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: ✨ feature

#290 피드 신고시 discord 알림 기능 구현
  src/main/java/com/depromeet/stonebed/domain/discord/application/DiscordNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/report/application/ReportService.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/infra/properties/DiscordProperties.java
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/resources/application.yml
Labels: ✨ feature

#291 feat: 댓글 생성 시 푸시 알림
  src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotificationType.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
Labels: ✨ feature, 🥇 P1

#292 feat: 피드 댓글 count 추가
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/FindFeedDto.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: ✨ feature, 🥇 P1

#294 feat: 미션 완료 image url 컬럼 추가
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: ✨ feature, 🥇 P1

#297 fix: 푸시 알림 메세지 조건 수정
  src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
Labels: 🐛 bug/error, 🥇 P1

#300 feat: 단일 피드 조회 API
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: ✨ feature, 🥇 P1

#302 fix: 알림 리스트 필터 제거
  src/main/java/com/depromeet/stonebed/domain/discord/application/DiscordNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
Labels: 🐛 bug/error, 🥇 P1

#304 feat: v2 엔드 포인트 및 모델 추가
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedContentGetResponseV2.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedGetResponseV2.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: ✨ feature, 🥇 P1

#306 refactor: 딥링크 수정
  src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
Labels: ♻️ refactor, 🥇 P1

#312 Fcm 스케쥴러 BatchEntry ID 값 UUID로 수정
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordControllerTest.java
Labels: 🐛 bug/error

#314 refactor: 알림 변수 상수화 및 메서드 분리
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
  src/main/java/com/depromeet/stonebed/global/common/constants/NotificationConstants.java
Labels: ♻️ refactor, 🥇 P1

#317 test: 댓글 테스트 코드
  src/main/java/com/depromeet/stonebed/domain/comment/dto/request/CommentCreateRequest.java
  src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java
Labels: 🧪 test, 🥈 P2

#316 fix: 회원 탈퇴 시 탈퇴자 댓글 예외 처리
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
  src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/comment/domain/Comment.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/FindFeedDto.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v1/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/v2/FeedContentGetResponseV2.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: 🐛 bug/error, ♻️ refactor, 🥇 P1

#320 refactor: 신고 엔티티 구조 변경
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/report/api/ReportController.java
  src/main/java/com/depromeet/stonebed/domain/report/application/ReportService.java
  src/main/java/com/depromeet/stonebed/domain/report/dao/ReportRepository.java
  src/main/java/com/depromeet/stonebed/domain/report/domain/Report.java
  src/main/java/com/depromeet/stonebed/domain/report/domain/ReportDomain.java
  src/main/java/com/depromeet/stonebed/domain/report/dto/request/ReportCreateRequest.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: ♻️ refactor, 🥇 P1

#322 chore: 배포 버전 workflow 추가 구성
  .github/workflows/develop-deploy.yml
  .github/workflows/production-deploy.yml
  src/main/java/com/depromeet/stonebed/domain/comment/application/CommentService.java
  src/test/java/com/depromeet/stonebed/domain/comment/application/CommentServiceTest.java
Labels: 🥇 P1
