Repository depromeet/WalWal-server, pull requests merged in 2024-09, with the labels that each got.

#246 FCM 부스터 알림 기능 로직 수정
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
Labels: 🐛 bug/error

#253 FCM 알림리스트 조회 시 deeplink 추가
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
Labels: ✨ feature, 🥇 P1

#257 Fcm 메세지에 deepLink 페이로드 설정
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmMessage.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
Labels: ✨ feature

#255 feat: 미션 완료 카드 Response 필드 추가
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1

#261 fix: 회원가입 시 default image 갱신
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
Labels: 🐛 bug/error, 🥇 P1

#259 feat: 미션 기록 display 필드 추가 및 로직 변경
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordDisplay.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1

#265 fix: 회원가입 시 image null 처리
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
Labels: 🐛 bug/error, 🥇 P1

#262 v1.1.0
  README.md
  images/IA.png
  images/app_qr.png
  images/cloud-architecture.png
  images/intro.png
  images/introduction.png
  images/tech-stack.png
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmMessage.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordDisplay.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: deploy

#267 v1.1.1
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
Labels: deploy

#268 v1.1.2
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
Labels: deploy

#270 refactor: fcm service 통합
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmNotificationController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
Labels: ♻️ refactor, 🥈 P2

#272 fix: token not found throw 하지 않도록 수정
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
Labels: 🐛 bug/error, 🥇 P1

#273 v1.1.3
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmNotificationController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
  src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java
  src/main/java/com/depromeet/stonebed/global/config/sqs/SqsConfig.java
  src/main/java/com/depromeet/stonebed/global/config/swagger/SwaggerConfig.java
  src/main/java/com/depromeet/stonebed/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/depromeet/stonebed/global/security/JwtTokenProvider.java
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
  src/main/java/com/depromeet/stonebed/scheduler/missionRecord/MissionRecordScheduler.java
  src/test/java/com/depromeet/stonebed/config/TestQuerydslConfig.java
  src/test/java/com/depromeet/stonebed/config/TestRedisConfig.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/JwtTokenProviderTest.java
  src/test/java/com/depromeet/stonebed/domain/auth/dao/RefreshTokenRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmSchedulerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/Order.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/User.java
Labels: deploy

#276 FCM 푸시 알림, 유효하지 않은 FCM토큰 삭제
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmTokenRepository.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
Labels: 🐛 bug/error

#275 feat: 댓글 엔티티 구현
  src/main/java/com/depromeet/stonebed/domain/comment/dao/CommentRepository.java
  src/main/java/com/depromeet/stonebed/domain/comment/domain/Comment.java
Labels: ✨ feature, 🥇 P1

#278 FCM 메세지 저장시 null값 중복으로 인해 에러발생, token값 null인것 대상에서 제외
  src/main/java/com/depromeet/stonebed/scheduler/fcm/FcmScheduler.java
Labels: 🐛 bug/error

#281 feat: 미션 기록 완료 리스트
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordTabListResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1

#284 fix: missionRecordStatus 필드 추가
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordTabListResponse.java
Labels: 🐛 bug/error, 🥇 P1
