Repository depromeet/WalWal-server, pull requests merged in 2024-08, with the labels that each got.

#66 [WALWAL-150] missionrecord imageupload 기능 구현
  src/main/java/com/depromeet/stonebed/domain/image/api/ImageController.java
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionRecordImageCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionRecordImageUploadRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordStatus.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCreateResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: ✨ feature

#71 [WALWAL-151] 데일리미션 일러스트, 컬러값 추가
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetTodayResponse.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
Labels: ✨ feature, 🥇 P1

#68 [WALWAL-155] 카카오 로그인/회원가입 구현
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/JwtTokenService.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/apple/AppleClient.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/kakao/KakaoClient.java
  src/main/java/com/depromeet/stonebed/domain/auth/dto/request/AppleTokenRequest.java
  src/main/java/com/depromeet/stonebed/domain/auth/dto/response/AppleTokenResponse.java
  src/main/java/com/depromeet/stonebed/domain/auth/dto/response/KakaoAuthResponse.java
  src/main/java/com/depromeet/stonebed/global/common/constants/SecurityConstants.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: ✨ feature, 🥇 P1

#74 [WALWAL-161] 임시 토큰 여부 판별
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/dto/request/RefreshTokenRequest.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/CreateMemberRequest.java
Labels: 🐛 bug/error, 🥇 P1

#77 [WALWAL-163] 배포 환경 메모리 제한
  docker-compose.yaml
Labels: 🥇 P1, ⚙️ chore

#75 [WALWAL-160] 미션 시작 시 동시성 문제 개선
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1

#82 [WALWAL-157] 회원탈퇴 API
  src/main/java/com/depromeet/stonebed/domain/auth/api/AuthController.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/JwtTokenService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: ✨ feature, 🥇 P1

#85 [WALWAL-154] PROD 운영 서버 워크플로 작성
  .github/workflows/production-build-deploy.yml
  src/main/java/com/depromeet/stonebed/domain/auth/application/apple/AppleClient.java
Labels: ⚙️ chore, 🥈 P2

#90 hotfix: EC2 도커 단일 인스턴스 배포
  .github/workflows/develop-build-deploy.yml
  .github/workflows/production-build-deploy.yml
  Dockerfile
  docker-compose.yaml
Labels: 🐛 bug/error

#86 [WALWAL-156] 팔로우 추가 및 취소, 조회 기능
  src/main/java/com/depromeet/stonebed/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/stonebed/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/stonebed/domain/follow/dao/FollowRepository.java
  src/main/java/com/depromeet/stonebed/domain/follow/domain/Follow.java
  src/main/java/com/depromeet/stonebed/domain/follow/dto/request/FollowCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowRelationMemberResponse.java
  src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowStatus.java
  src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowedMemberResponse.java
  src/main/java/com/depromeet/stonebed/domain/follow/dto/response/FollowerDeletedResponse.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/follow/application/FollowServiceTest.java
Labels: ✨ feature, 🥇 P1

#81 [WALWAL-164] 닉네임 검증
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/NicknameCheckRequest.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: ✨ feature, 🥇 P1

#91 [WALWAL-167] Mission Response 및 API PathVariable 수정
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetTodayResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
Labels: ♻️ refactor

#79 [WALWAL-163] 스웨거 문서 이름 일관적으로 포매팅
  src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
Labels: 📄 doc s, 🥉 P3

#99 test: SecurityUtil 테스트 코드 추가
  src/test/java/com/depromeet/stonebed/global/util/SecurityUtilTest.java
Labels: 🧪 test, 🥈 P2

#100 test: RefreshToken 테스트
  .github/workflows/develop-build-deploy.yml
  .github/workflows/develop-pull-request-on-check.yml
  .github/workflows/production-build-deploy.yml
  docker-compose-test.yaml
  src/test/java/com/depromeet/stonebed/TestRedisConfig.java
  src/test/java/com/depromeet/stonebed/domain/auth/dao/RefreshTokenRepositoryTest.java
Labels: 🧪 test, 🥈 P2

#101 fix: 온보딩 Default imageUrl 요청 필드 추가
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/CreateMemberRequest.java
Labels: 🐛 bug/error, 🥇 P1

#92 [WALWAL-165] FCM 푸시 알림 기능 구현
  .github/workflows/develop-build-deploy.yml
  build.gradle
  docker-compose.yaml
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmResponseErrorType.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/request/FcmSendRequest.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/request/FcmTokenRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/global/config/fcm/FcmConfig.java
  src/main/java/com/depromeet/stonebed/global/config/schedule/ScheduleConfig.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/global/util/FcmNotificationUtil.java
  src/main/java/com/depromeet/stonebed/infra/properties/FcmProperties.java
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/resources/application.yml
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/follow/application/FollowServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: ✨ feature, 🥈 P2

#103 [WALWAL-168] MissionRecord에 Text값 추가
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ♻️ refactor, 🥇 P1

#93 [WALWAL-149] Auth, Member 테스트 코드 작성
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/dto/AuthenticationToken.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/NicknameCheckRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/JwtTokenServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtilTest.java
Labels: 🧪 test, 🥈 P2

#98 test: MemberUtil 테스트 코드 추가
  src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java
Labels: 🧪 test, 🥈 P2

#108 chore: prod workflow 작성
  .github/workflows/develop-build-deploy.yml
  .github/workflows/production-build-deploy.yml
Labels: 🥇 P1, ⚙️ chore

#112 fix: prod 환경 Swagger 동작
  src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java
Labels: 🐛 bug/error, 🥇 P1

#104 [WALWAL-159] 피드 작업
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepository.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedGetResponse.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: ✨ feature

#113 refactor: fixtureMonkey setUp 함수 추상 클래스로 상속으로 개선
  src/test/java/com/depromeet/stonebed/FixtureMonkeySetUp.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/JwtTokenServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/follow/application/FollowServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java
  src/test/java/com/depromeet/stonebed/global/util/SecurityUtilTest.java
  src/test/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtilTest.java
Labels: ♻️ refactor, 🧪 test, 🥇 P1

#117 [WALWAL-170] 매일 IN_PROGRESS -> NOT_COMPLETED로 변경해주는 스케쥴러 구현
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: ✨ feature, 🥇 P1

#127 refactor: MissionRecord API `Path` -> `Query`/`Body` 로 수정
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordStartRequest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ♻️ refactor

#119 fix: withdraw temporary role 갱신
  src/main/java/com/depromeet/stonebed/domain/auth/api/AuthController.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
Labels: 🐛 bug/error, 🥇 P1

#124 chore: prometheus 구성
  build.gradle
  src/main/resources/application-actuator.yml
Labels: ⚙️ chore, 🥈 P2

#128 feat: 프로필 수정
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/MemberProfileUpdateRequest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
Labels: ✨ feature, 🥇 P1

#133 fix: totalCount DTO 변환
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCompleteTotal.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: 🐛 bug/error, 🥇 P1

#132 refactor: 다른 유저 캘린더 조회 및 GET 요청으로 변경
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ♻️ refactor, 🥇 P1

#134 [WALWAL-171] mission image upload
  src/main/java/com/depromeet/stonebed/domain/image/api/ImageController.java
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/image/domain/ImageType.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionImageCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MissionImageUploadRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordSaveRequest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ✨ feature, 🥈 P2

#130 feature: 부스트 API
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/FindFeedDto.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedBoostRequest.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/test/java/com/depromeet/stonebed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: ✨ feature

#137 feature: 부스트 위치 변경 및 피드 컨텐츠 추가
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordBoostRequest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ✨ feature, ♻️ refactor, 🥇 P1

#141 fix: MemberRole 반영이 되지 않는 현상
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: 🐛 bug/error, 🥇 P1

#144 feature: 피드 사용자 닉네임 프로필 정보 추가 및 미션 이름 추가
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
Labels: ✨ feature, 🥇 P1

#146 fix: invalidateTokenForCurrentMember메서드 추가 및 수정
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
Labels: 🐛 bug/error

#149 hotfix: today API before -> after 수정
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
Labels: 🐛 bug/error, 🥇 P1

#142 [WALWAL-173] fcm alarm list 구현
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotificationType.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: ✨ feature, 🥇 P1

#151 chore: nginx log추가
  docker-compose.yaml
Labels: ⚙️ chore

#154 fix: 닉네임 검증 로직 수정
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java
Labels: 🐛 bug/error, 🥇 P1

#156 fix: PR 업 워크플로 수정
  .github/workflows/develop-build-deploy.yml
  .github/workflows/develop-pull-request-on-check.yml
Labels: 🐛 bug/error, 🥇 P1

#158 fix: 동일한 fcm_token 저장 오류 해결
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: 🐛 bug/error, 🥇 P1

#161 fix: 피드 커서 파싱 오류 핸들링 및 본인 기록만 나오는 문제 해결
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: 🐛 bug/error, 🥈 P2

#162 refactor: 회원 정보 DTO
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/response/MemberInfoResponse.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
Labels: ♻️ refactor, 🥇 P1

#163 v0.0.4
  .github/workflows/develop-build-deploy.yml
  .github/workflows/develop-pull-request-on-check.yml
  docker-compose.yaml
  nginx/default.conf
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotificationType.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationDto.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dto/response/FcmNotificationResponse.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/global/common/constants/FcmNotificationConstants.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: deploy

#166 fix: nullable=true처리
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
Labels: 🐛 bug/error

#169 fix: FCM token nullable true
  nullable_true
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
Labels: 🐛 bug/error

#168 [WALWAL-174] raisepet mission supply
  src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/mission/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
Labels: ✨ feature

#171 hotifx: mission_image 업로드 수정
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
Labels: 🐛 bug/error

#170 fix: 회원탈퇴 데이터 초기화
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/common/BaseFullTimeEntity.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmToken.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: 🐛 bug/error, ♻️ refactor, 🥇 P1

#176 fix: today 미션 raisePet에 따라 미션 할당
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
Labels: 🐛 bug/error, 🥇 P1

#177 Fcm 알림 리스트 로직 수정 및 nextCursor=nil 처리
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
Labels: 🐛 bug/error

#179 fix: 피드 nextCursor=null 처리 및 미션기록 상태 완료만 나오도록 처리 & 멤버 파라메터 추가
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
  src/test/java/com/depromeet/stonebed/domain/feed/application/FeedServiceTest.java
Labels: 🐛 bug/error, 🥇 P1

#182 chore: prod ddl-auto update
  src/main/resources/application-prod.yml
Labels: ⚙️ chore, 🥈 P2

#184 fix: 피드 조회 `fetchOne` -> `fetchFirst` 로수정
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
Labels: 🐛 bug/error, 🥇 P1

#187 FCM 알림 메세지 전송 시 member 객체의 status가 NORMAL일 경우에만 전송
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
Labels: 🐛 bug/error

#189 미션 기록 트랜잭션 전파수준 설정
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
Labels: 🐛 bug/error

#191 Fcm 리마인드 알림 조건 수정
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
Labels: 🐛 bug/error

#180 chore: loki, promtail logging 구성
  .gitignore
  build.gradle
  src/main/java/com/depromeet/stonebed/global/config/web/WebConfig.java
  src/main/java/com/depromeet/stonebed/global/interceptor/MdcLoggingInterceptor.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ⚙️ chore, 🥈 P2

#193 Fcm 알림 메세지 전송 시 token is not null 조건 추가
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryImpl.java
Labels: 🐛 bug/error

#196 v0.0.6
  .gitignore
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmTokenService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarDto.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
  src/main/java/com/depromeet/stonebed/global/config/web/WebConfig.java
  src/main/java/com/depromeet/stonebed/global/interceptor/MdcLoggingInterceptor.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
Labels: deploy

#198 refactor: 다른 유저 complete totalCount 조회
  nullable_true
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ♻️ refactor

#201 v0.0.8
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/missionHistory/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: deploy

#202 v0.0.9
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
Labels: deploy

#203 v0.0.10
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordIdResponse.java
Labels: deploy

#206 fix: missionHistory 분리
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/domain/MissionHistory.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ♻️ refactor, 🥇 P1

#208 Fcm 데일리, 리마인드 메서드 통일
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
Labels: 🐛 bug/error

#213 미션 기록, Fcm 컨트롤러 메서드 명 수정
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
Labels: 🐛 bug/error

#211 refactor: 피드 API 쿼리 파라메터 검증 코드 리팩토링
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
Labels: ♻️ refactor, 🥉 P3

#217 ImageUrl null 체크검증
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: 🐛 bug/error

#219 MissionRecord TabResponse recordId 제거
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
Labels: 🐛 bug/error

#220 v0.1.0
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/stonebed/domain/feed/dao/FeedRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/request/FeedGetRequest.java
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/dao/MissionHistoryRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionHistory/domain/MissionHistory.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionTabResponse.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: deploy

#222 미션 기록 NOT_COMPLETED 스케쥴러 시간 기준으로 변경
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🐛 bug/error

#224 미션 탭바 관련 테스트 코드 작성
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: 🧪 test

#226 feat: 회원 정보 조회 API
  .gitignore
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/kakao/KakaoClient.java
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
Labels: ✨ feature, 🥇 P1

#227 v0.1.1
  .gitignore
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/auth/application/kakao/KakaoClient.java
  src/main/java/com/depromeet/stonebed/domain/member/api/MemberController.java
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: deploy

#230 미션 기록 캘린더 중복 로직 수정
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: 🐛 bug/error

#231 fix: 본인 nickname 검증
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java
Labels: 🐛 bug/error, 🥇 P1

#233 미션 기록 캘린더 COMPLETED인 데이터만 조회
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
Labels: 🐛 bug/error

#237 v0.1.2
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
  src/test/java/com/depromeet/stonebed/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/global/util/MemberUtilTest.java
Labels: deploy

#235 feature: 피드 미션완료 필드 추가
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionCreateResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetOneResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionUpdateResponse.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
Labels: ✨ feature, 🧪 test, 🥈 P2

#215 feature: 내 피드인 경우 예외 400 (Bad Request) 처리 추가
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: ✨ feature, 🧪 test, 🥈 P2

#238 FCM 알림 서비스 SQS + Lambda 리팩토링
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmMessage.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
  src/main/java/com/depromeet/stonebed/global/config/fcm/FcmConfig.java
  src/main/java/com/depromeet/stonebed/global/config/sqs/SqsConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/FcmProperties.java
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/SqsProperties.java
  src/main/resources/application-cloud.yml
  src/main/resources/application.yml
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: ✨ feature, ♻️ refactor

#241 fix: 회원탈퇴 데이터 삭제 방식 변경
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: 🐛 bug/error, 🥇 P1

#242 v0.1.3
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/api/FcmController.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/application/FcmService.java
  src/main/java/com/depromeet/stonebed/domain/fcm/dao/FcmNotificationRepository.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmMessage.java
  src/main/java/com/depromeet/stonebed/domain/fcm/domain/FcmNotification.java
  src/main/java/com/depromeet/stonebed/domain/feed/dto/response/FeedContentGetResponse.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionCreateResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetOneResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionUpdateResponse.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordBoost.java
  src/main/java/com/depromeet/stonebed/domain/sqs/application/SqsMessageService.java
  src/main/java/com/depromeet/stonebed/global/config/fcm/FcmConfig.java
  src/main/java/com/depromeet/stonebed/global/config/sqs/SqsConfig.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/infra/properties/FcmProperties.java
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/SqsProperties.java
  src/main/resources/application-cloud.yml
  src/main/resources/application.yml
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmNotificationServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/fcm/application/FcmScheduledServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordServiceTest.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: deploy

#243 hotfix: boost recordIds로 삭제
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: 🐛 bug/error, 🥇 P1

#244 v0.1.4
  src/main/java/com/depromeet/stonebed/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordBoostRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/test/java/com/depromeet/stonebed/domain/auth/application/AuthServiceTest.java
Labels: deploy

#248 hotfix: oauth_email unique 제약 조건 삭제
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
Labels: 🐛 bug/error, 🥇 P1

#249 v1.0.0
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
Labels: deploy
