Repository depromeet/WalWal-server, pull requests merged in 2024-06, with the labels that each got.

#2 chore: 프로젝트 세팅
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/⚙️-chore.md
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/📝-documentation.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🥇 P1, ⚙️ chore

#7 chore: develop PR on check workflow 작성
  .github/workflows/develop-pull-request-on-check.yml
Labels: 🥇 P1, ⚙️ chore

#8 chore: Spring Actuator 구성
  build.gradle
  src/main/resources/application.yml
Labels: 🥇 P1, ⚙️ chore

#12 chore: domain 구조 아키텍처 구성
  src/main/java/com/depromeet/stonebed/domain/common/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/api/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/application/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/dao/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/domain/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/dto/.gitkeep
  src/main/java/com/depromeet/stonebed/global/common/.gitkeep
  src/main/java/com/depromeet/stonebed/global/config/.gitkeep
  src/main/java/com/depromeet/stonebed/global/error/.gitkeep
  src/main/java/com/depromeet/stonebed/global/security/.gitkeep
  src/main/java/com/depromeet/stonebed/global/util/.gitkeep
  src/main/java/com/depromeet/stonebed/infra/.gitkeep
Labels: 🥇 P1, ⚙️ chore

#14 [WALWAL-96] SwaggerConfig 작성
  build.gradle
  src/main/java/com/depromeet/stonebed/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙️ chore, 🥈 P2

#19 [WALWAL-104] Spotless 구성
  .github/workflows/develop-pull-request-on-check.yml
  build.gradle
  scripts/pre-commit
  src/main/java/com/depromeet/stonebed/StonebedApplication.java
  src/main/java/com/depromeet/stonebed/global/config/SwaggerConfig.java
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
Labels: 🥇 P1, ⚙️ chore

#16 [WALWAL-84] jacoco 세팅 추가
  build.gradle
Labels: ⚙️ chore, 🥈 P2

#22 [WALWAL-107] BaseTimeEntity 추가
  src/main/java/com/depromeet/stonebed/domain/common/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/common/BaseTimeEntity.java
  src/main/java/com/depromeet/stonebed/global/config/jpa/JpaConfig.java
Labels: ✨ feature, 🥇 P1

#26 [WALWAL-88] 회원 엔티티 구성
  src/main/java/com/depromeet/stonebed/domain/common/BaseTimeEntity.java
  src/main/java/com/depromeet/stonebed/domain/member/dao/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/.gitkeep
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/MemberRole.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/MemberStatus.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Profile.java
  src/main/java/com/depromeet/stonebed/global/config/.gitkeep
  src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
Labels: ✨ feature, 🥇 P1
