Repository depromeet/WalWal-server, pull requests merged in 2024-07, with the labels that each got.

#30 [WALWAL-114] record -> class 변경
  src/main/java/com/depromeet/stonebed/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Profile.java
Labels: 🐛 bug/error, 🥇 P1

#23 [WALWAL-109] GlobalResponse를 위한 RestControllerAdvice 세팅
  src/main/java/com/depromeet/stonebed/global/common/response/ApiResponse.java
  src/main/java/com/depromeet/stonebed/global/common/response/ApiResponseAdvice.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorResponse.java
  src/main/java/com/depromeet/stonebed/global/error/exception/CustomException.java
  src/main/java/com/depromeet/stonebed/global/error/exception/GlobalExceptionHandler.java
Labels: 🥇 P1, ⚙️ chore

#32 [WALWAL-115] 미션 엔티티 구현
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
Labels: ✨ feature, 🥇 P1

#28 [WALWAL-106] fixtureMonkey 도입
  .gitignore
  build.gradle
  src/main/resources/application.yml
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/Order.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/User.java
  src/test/resources/application-test.yml
Labels: ⚙️ chore, 🥈 P2

#37 [WALWAL-105] redis 환경 구성
  build.gradle
  src/main/java/com/depromeet/stonebed/infra/.gitkeep
  src/main/java/com/depromeet/stonebed/infra/config/RedisConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/RedisProperties.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/test/java/com/depromeet/stonebed/StonebedApplicationTests.java
  src/test/java/com/depromeet/stonebed/domain/member/domain/MemberTest.java
Labels: 🥇 P1, ⚙️ chore

#35 [WALWAL-113] SecurityConfig 및 유틸리티 구현
  build.gradle
  src/main/java/com/depromeet/stonebed/global/common/.gitkeep
  src/main/java/com/depromeet/stonebed/global/common/constants/SwaggerUrlConstants.java
  src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java
  src/main/java/com/depromeet/stonebed/global/error/.gitkeep
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/global/security/.gitkeep
  src/main/java/com/depromeet/stonebed/global/security/PrincipalDetails.java
  src/main/java/com/depromeet/stonebed/global/util/.gitkeep
  src/main/java/com/depromeet/stonebed/global/util/MemberUtil.java
  src/main/java/com/depromeet/stonebed/global/util/SecurityUtil.java
Labels: 🥇 P1, ⚙️ chore

#34 [WALWAL-116] 미션 기록 엔티티 구현
  src/main/java/com/depromeet/stonebed/domain/record/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/record/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/record/domain/MissionStatus.java
Labels: ✨ feature, 🥇 P1

#38 [WALWAL-110] elastic beanstalk dev 서버 workflow 작성
  .github/workflows/develop-build-deploy.yml
  .github/workflows/develop-pull-request-on-check.yml
  Dockerfile
  Dockerrun.aws.json
Labels: 🥇 P1, ⚙️ chore

#41 [WALWAL-123] Elastic BeanStalk 배포 version Label
  .github/workflows/develop-build-deploy.yml
Labels: 🐛 bug/error, 🥇 P1

#42 [WALWAL-132] application yml 분리
  .env.example
  src/main/java/com/depromeet/stonebed/infra/properties/PropertiesConfig.java
  src/main/java/com/depromeet/stonebed/infra/properties/S3Properties.java
  src/main/resources/application-actuator.yml
  src/main/resources/application-cloud.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-docs.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🥇 P1, ⚙️ chore

#46 [WALWAL-135] missionrecord crud 구현
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionStatus.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCreateResponse.java
  src/main/java/com/depromeet/stonebed/global/common/response/ApiResponseAdvice.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
Labels: ✨ feature, 🥈 P2

#45 [WALWAL-138]: mission crud 구현
  src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionCreateResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetOneResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionUpdateResponse.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
Labels: ✨ feature, 🥇 P1

#50 [WALWAL-142] EB docker-compose 구성
  .github/workflows/develop-build-deploy.yml
  Dockerrun.aws.json
  docker-compose.yaml
  nginx/default.conf
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
Labels: 🥇 P1, ⚙️ chore

#56 [WALWAL-148] Dev, Prod 환경 분리
  .github/workflows/develop-build-deploy.yml
  docker-compose.yaml
  src/main/java/com/depromeet/stonebed/global/annotation/ConditionalOnProfile.java
  src/main/java/com/depromeet/stonebed/global/annotation/OnProfileCondition.java
  src/main/java/com/depromeet/stonebed/global/common/constants/EnvironmentConstants.java
  src/main/java/com/depromeet/stonebed/global/config/security/WebSecurityConfig.java
  src/main/java/com/depromeet/stonebed/global/config/swagger/SwaggerConfig.java
  src/main/java/com/depromeet/stonebed/global/util/CookieUtil.java
  src/main/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtil.java
  src/main/resources/application-dev.yml
  src/test/java/com/depromeet/stonebed/fixtureMonkeyTest/TestFixtureMonkey.java
  src/test/java/com/depromeet/stonebed/global/util/SpringEnvironmentUtilTest.java
Labels: ✨ feature, 🥇 P1

#52 [WALWAL-145] missionrecord calendarview
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/request/MissionRecordCalendarRequest.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarDto.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1

#58 [WALWAL-122] 이미지 업로드 기능
  build.gradle
  src/main/java/com/depromeet/stonebed/domain/auth/application/apple/AppleClient.java
  src/main/java/com/depromeet/stonebed/domain/image/api/ImageController.java
  src/main/java/com/depromeet/stonebed/domain/image/application/ImageService.java
  src/main/java/com/depromeet/stonebed/domain/image/dao/ImageRepository.java
  src/main/java/com/depromeet/stonebed/domain/image/domain/Image.java
  src/main/java/com/depromeet/stonebed/domain/image/domain/ImageFileExtension.java
  src/main/java/com/depromeet/stonebed/domain/image/domain/ImageType.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MemberProfileImageCreateRequest.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/request/MemberProfileImageUploadCompleteRequest.java
  src/main/java/com/depromeet/stonebed/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/stonebed/global/common/constants/UrlConstants.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/main/java/com/depromeet/stonebed/infra/config/redis/RedisConfig.java
  src/main/java/com/depromeet/stonebed/infra/config/s3/S3Config.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
Labels: ✨ feature, 🥇 P1

#62 [WALWAL-152] register Request Body 불필요한 필드 삭제
  src/main/java/com/depromeet/stonebed/domain/member/application/MemberService.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/MarketingAgreement.java
  src/main/java/com/depromeet/stonebed/domain/member/domain/Member.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/CreateNewUserDTO.java
  src/main/java/com/depromeet/stonebed/domain/member/dto/request/CreateMemberRequest.java
Labels: 🐛 bug/error, 🥇 P1

#53 [WALWAL-147] 오늘의 미션 API 추가
  src/main/java/com/depromeet/stonebed/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/stonebed/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/stonebed/domain/mission/domain/MissionHistory.java
  src/main/java/com/depromeet/stonebed/domain/mission/dto/response/MissionGetTodayResponse.java
  src/main/java/com/depromeet/stonebed/global/error/ErrorCode.java
  src/test/java/com/depromeet/stonebed/domain/mission/api/MissionControllerTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/application/MissionServiceTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionHistoryRepositoryTest.java
  src/test/java/com/depromeet/stonebed/domain/mission/dao/MissionRepositoryTest.java
Labels: ✨ feature, 🥇 P1

#64 [WALWAL-153] 미션 n번째 카운트 기능 추가
  src/main/java/com/depromeet/stonebed/domain/image/api/ImageController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/stonebed/domain/missionRecord/domain/MissionRecordStatus.java
  src/test/java/com/depromeet/stonebed/domain/missionRecord/MissionRecordServiceTest.java
Labels: ✨ feature, 🥇 P1
